name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: removeExisting
      run: ls
    - name: makeFolder
      run: mkdir build
    - name: compile
      run: CC=clang cmake .
    - name: cd
      run: cd build
    - name: compile2
      run: make
    - name: run
      run: ./tests/utility_fuzzer_test -max_total_time=60
